name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "p27yfym5g8r4xtirvrimg42j"
  title = "Download Angular, then Create & Implement angstandalone directory"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "izzffip4i0c1hfr2h1dknetw"
  title = "Create new branch 'mynodebranch', and create node server without express, then create plainnode directory"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "q7dxfwzt4ldezip30g0in9gi"
  title = "In 'mynodebranch' create node server using express, in new 'nodeexpress' directory"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "x83xt1xd3hllmeqx27xt6elj"
  title = "In 'mynodebranch', create mongonode directory"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "gsec4exosyuzlrhb6ab9xcpj"
  title = "Download and create mongodb for collection Users given by professor"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "oqghzm4ufeudcplqttxbq0wk"
  title = "Create & Implement MERN website server"
  description = "<p>Download a few things &amp; modify index.js &amp; some nodes in client directory</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "y5emenof207kvdqxgmu1v88m"
  title = "Create & Implement MEVN website server"
  description = "<p>Download a few things &amp; modify index.js &amp; some nodes in client directory</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "dxmk12o2vvef16tz3p6vs5wq"
  title = "Create TRS Directory and MEAN and MERN projects"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "sfabhoju9blz4xthlrrnxli5"
  title = "Create Kanpilot for Project_1"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "cheq28mxtfejw3a8drwr5fcw"
  title = "Create & Implement mongonode using mongodb"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "oy6jexaaifp3ci6g9kheac85"
  title = "Download & Install Google Chrome in WSL"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "l53j4hp3gzkoy8caaku0mf2q"
  title = "Create new branch, 'myvuebranch', Download Vue , then Create & Implement v-standalone directory"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "d1mdqpnh15p4s29y4ct4hlfn"
  title = "Create new beanch, 'myreactbranch', and Download React, then Create & Implment rstandalone directory"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
